proxy:
    image: jwilder/nginx-proxy
    ports:
        - "3000:80"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
web:
    build: .
    ports:
        - "5000"
    volumes:
        - .:/code
    links:
        - redis
    environment:
        - VIRTUAL_HOST=192.168.99.100
        - VIRTUAL_PORT=5000
redis:
    image: redis
